version: '3.9'
services:
  postgres:
    image: 'postgres:14.3'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}
