name: Build docker image

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build image
        run: docker build . --file Dockerfile
        env:
          PORT: $PORT
